name: Build

on: push
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  analyze-code:
    name: "Analyze code"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
      - uses: actions/checkout@v2
      - run: ./gradlew detekt
