name: Build

on: push
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  analyze-code:
    needs: validation
    name: "Analyze code"
    runs-on: ubuntu-latest
    env:
      DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew detekt
      - run: ./gradlew lint
  build-debug:
    needs: analyze-code
    name: "Build debug"
    runs-on: ubuntu-latest
    env:
      DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew :app:assembleDebug
  build-release:
    needs: analyze-code
    name: "Build release"
    runs-on: ubuntu-latest
    env:
      DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew :app:assembleRelease
